import Link from "next/link";
import type { Outlet } from "@prisma/client";
import ChannelPicker, { type ChannelOption } from "@/components/ChannelPicker";
import { PAYMENT_TERMS, VISIT_DAYS } from "@/lib/masterdata";

export type OutletFormValues = Partial<Record<string, string>>;

// Shared by "New outlet" and "Edit outlet". `values` carries what the user typed when the
// server sent them back (for example to show a duplicate warning).
export default function OutletForm({
  action,
  outlet,
  values = {},
  branches,
  channels,
  routes,
  duplicates = [],
  submitLabel,
}: {
  action: (formData: FormData) => void | Promise<void>;
  outlet?: Outlet;
  values?: OutletFormValues;
  branches: { id: string; name: string }[];
  channels: ChannelOption[];
  routes: { id: string; name: string; status: string }[];
  duplicates?: { id: string; name: string; address: string; code: string | null; status: string }[];
  submitLabel: string;
}) {
  const v = (k: string, fallback: string | number | null | undefined = "") => String(values[k] ?? fallback ?? "");
  return (
    <form action={action} className="space-y-4">
      {outlet && <input type="hidden" name="id" value={outlet.id} />}

      {duplicates.length > 0 && (
        <div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">
          <p className="font-semibold">Possible duplicate outlet</p>
          <p className="mt-1 text-xs">An outlet with the same name and address, or at almost the same GPS position, already exists:</p>
          <ul className="mt-2 space-y-1">
            {duplicates.map((d) => (
              <li key={d.id} className="flex items-center justify-between text-xs">
                <span>
                  {d.name} — {d.address} <span className="text-amber-700">({d.code ?? "no code"}, {d.status})</span>
                </span>
                <Link href={`/admin/outlets/${d.id}`} className="text-blue-700 underline">Open the existing record</Link>
              </li>
            ))}
          </ul>
          <label className="mt-3 flex items-center gap-2 text-xs">
            <input type="checkbox" name="confirmDuplicate" value="1" /> Save anyway — this is a different outlet
          </label>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="label" htmlFor="name">Outlet (trading) name</label>
          <input className="input" id="name" name="name" defaultValue={v("name", outlet?.name)} required />
        </div>
        <div>
          <label className="label" htmlFor="ownerName">Owner / key contact</label>
          <input className="input" id="ownerName" name="ownerName" defaultValue={v("ownerName", outlet?.ownerName)} />
        </div>
      </div>
      {outlet?.code && (
        <p className="text-xs text-slate-500">
          Outlet code <span className="font-mono font-medium text-slate-700">{outlet.code}</span> — generated by the platform and shared with the SFA app.
        </p>
      )}

      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="label" htmlFor="branchId">Branch</label>
          <select className="input" id="branchId" name="branchId" defaultValue={v("branchId", outlet?.branchId)} required>
            {branches.map((b) => (
              <option key={b.id} value={b.id}>{b.name}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="label" htmlFor="routeId">Route</label>
          <select className="input" id="routeId" name="routeId" defaultValue={v("routeId", outlet?.routeId)} required>
            <option value="" disabled>Select a route</option>
            {routes
              .filter((r) => r.status === "active" || r.id === outlet?.routeId)
              .map((r) => (
                <option key={r.id} value={r.id}>{r.name}</option>
              ))}
          </select>
        </div>
      </div>

      <ChannelPicker channels={channels} channelId={v("channelId", outlet?.channelId)} subChannel={v("subChannel", outlet?.subChannel)} />
      {outlet && (
        <div>
          <label className="label" htmlFor="channelEffectiveFrom">If the channel is changed, effective from</label>
          <input className="input max-w-xs" id="channelEffectiveFrom" name="channelEffectiveFrom" type="date" defaultValue={new Date().toISOString().slice(0, 10)} />
          <p className="mt-1 text-xs text-slate-500">Pricing and promotion rules follow the new channel from this date; past transactions are unchanged.</p>
        </div>
      )}

      <div>
        <label className="label" htmlFor="address">Address (street, barangay, city, province)</label>
        <input className="input" id="address" name="address" defaultValue={v("address", outlet?.address)} required />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="label" htmlFor="lat">GPS latitude</label>
          <input className="input" id="lat" name="lat" type="number" step="0.0001" defaultValue={v("lat", outlet?.lat ?? 14.5995)} required />
        </div>
        <div>
          <label className="label" htmlFor="lng">GPS longitude</label>
          <input className="input" id="lng" name="lng" type="number" step="0.0001" defaultValue={v("lng", outlet?.lng ?? 120.9842)} required />
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <div>
          <label className="label" htmlFor="contactPerson">Contact person</label>
          <input className="input" id="contactPerson" name="contactPerson" defaultValue={v("contactPerson", outlet?.contactPerson)} />
        </div>
        <div>
          <label className="label" htmlFor="phone">Mobile</label>
          <input className="input" id="phone" name="phone" defaultValue={v("phone", outlet?.phone)} placeholder="09xx xxx xxxx" />
        </div>
        <div>
          <label className="label" htmlFor="landline">Landline</label>
          <input className="input" id="landline" name="landline" defaultValue={v("landline", outlet?.landline)} />
        </div>
      </div>
      <div className="grid grid-cols-3 gap-3">
        <div>
          <label className="label" htmlFor="email">Email</label>
          <input className="input" id="email" name="email" type="email" defaultValue={v("email", outlet?.email)} />
        </div>
        <div>
          <label className="label" htmlFor="visitDay">Visit day</label>
          <select className="input" id="visitDay" name="visitDay" defaultValue={v("visitDay", outlet?.visitDay)}>
            <option value="">Follow the route</option>
            {VISIT_DAYS.map((d) => (
              <option key={d} value={d}>{d[0].toUpperCase() + d.slice(1)}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="label" htmlFor="businessRegRef">Business registration ref.</label>
          <input className="input" id="businessRegRef" name="businessRegRef" defaultValue={v("businessRegRef", outlet?.businessRegRef)} />
        </div>
      </div>

      <div className="grid grid-cols-3 gap-3">
        <div>
          <label className="label" htmlFor="paymentTerms">Payment terms</label>
          <select className="input" id="paymentTerms" name="paymentTerms" defaultValue={v("paymentTerms", outlet?.paymentTerms ?? "credit_30")}>
            {PAYMENT_TERMS.map((t) => (
              <option key={t.id} value={t.id}>{t.label}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="label" htmlFor="creditLimit">Credit limit (₱)</label>
          <input className="input" id="creditLimit" name="creditLimit" type="number" defaultValue={v("creditLimit", outlet?.creditLimit ?? 50000)} />
        </div>
        {outlet && (
          <div>
            <label className="label" htmlFor="creditStatus">Credit status</label>
            <select className="input" id="creditStatus" name="creditStatus" defaultValue={outlet.creditStatus}>
              <option value="active">Active</option>
              <option value="on_watch">On watch</option>
              <option value="on_hold">On hold</option>
              <option value="blocked">Blocked</option>
            </select>
          </div>
        )}
      </div>

      {outlet && (
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="label" htmlFor="status">Outlet status</label>
            <select className="input" id="status" name="status" defaultValue={outlet.status}>
              <option value="active">Active</option>
              <option value="inactive">Inactive (withdrawn from coverage)</option>
              <option value="blocked">Blocked (barred from new orders)</option>
            </select>
            <p className="mt-1 text-xs text-slate-500">Outlets are never deleted — deactivating keeps all history.</p>
          </div>
          <div>
            <label className="label" htmlFor="blockedReason">Block reason</label>
            <input className="input" id="blockedReason" name="blockedReason" defaultValue={outlet.blockedReason ?? ""} placeholder="Required when blocking" />
          </div>
        </div>
      )}

      <div>
        <label className="label" htmlFor="remarks">Remarks</label>
        <input className="input" id="remarks" name="remarks" defaultValue={v("remarks", outlet?.remarks)} />
      </div>

      <div className="flex gap-2 pt-2">
        <button type="submit" className="btn-primary">{submitLabel}</button>
        <Link href="/admin/outlets" className="btn-secondary">Cancel</Link>
      </div>
    </form>
  );
}
